### ISSUE TITLE
Can not update deploy the cloud function anymore

### ISSUE THREAD

**Issue by adamm-alaoui-pro** [SnowWhiteEPFL/edweiss#33]
Hey, I have tried to deploy my new version the todo's cloud functions and then I got an error related to the `notif,ts` file. But I don't see it in my model.

**Comment by adamm-alaoui-pro** [comment]
Oh that's bizarre, are you sure that you are working on a clean tree ? Do a quick `git fetch` and `git pull`.

**Comment by adamm-alaoui-pro** [comment]
Can you check that you have in `edwiess-firebase/functions` an `.env` file. If not I will sent it to you via gmail. (Don't want that the whole internet have access to it publicly 🫣)

**Comment by adamm-alaoui-pro** [comment]
These is odd, I can't find it, can you send it to me, will it do the trick ?

**Comment by adamm-alaoui-pro** [comment]
Ah okay, now it fixed, the deploy cloud functions works just fine 🚀. Thank's for your time.

**Comment by adamm-alaoui-pro** [comment]
No worries 🎉.

**Comment by Gutogmaia** [comment]
Thank you for describing this issue I also had a similar one and did this exact process to fix it
