### ISSUE TITLE
Fix Component Detection Error in remotecontrol/index.test.tsx with React Native Testing Library Compatibility

### ISSUE THREAD

**Issue by TuanDangNguyen2003** [SnowWhiteEPFL/edweiss#36]
When running tests, the following error occurs:

> `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. There seems to be an issue with your configuration that prevents React Native Testing Library from working correctly.
Please check if you are using compatible versions of React Native and React Native Testing Library.`

This error may indicate an export issue or a compatibility problem between **React Native** and **React Native Testing Library**.

#### Task:
- Review component imports/exports to ensure they’re correctly structured.
- Verify that the versions of **React Native** and **React Native Testing Library** are compatible, and update them if needed.
- Implement fixes to prevent this error from recurring.

> **Note:** This branch `[fix/rmctl-test]` was created from `[test/tmctl]` to address this issue in tests and ensure compatibility.

**Comment by adamm-alaoui-pro** [comment]
Yeah you are right, maybe checkout the `lectureDoc` value. It seems to be undefined and only returning the `<TActivity ...>`, thus making no `RouterHeader` present in the screen.
