### ISSUE TITLE
EMERGENCY: Build from main not working due to "i18next could not be found"

### ISSUE THREAD

**Issue by TuanDangNguyen2003** [SnowWhiteEPFL/edweiss#45]
I tried to build an apk on the main branch but I countered this error `i8next could not be found` in `edweiss-app/config/i18config.ts`.

![image](https://github.com/user-attachments/assets/d3afe4d8-e060-4cc8-860a-895c449a2056)

I thought it is only because of my machine so I did `npm install i18next` but the problem persists. Solving this will allow us 1 step closer to having a functional build for demonstration on Friday.

**Comment by adamm-alaoui-pro** [comment]
That very odd.
Have you tried doing a quick `expo start -c` to clean up the cache on start of expo.

**Comment by TuanDangNguyen2003** [comment]
Sounds like a good idea to clear the cache. I will try that. Thanks!!

**Comment by holoisme** [comment]
Fixed in [8340ccd](https://github.com/SnowWhiteEPFL/edweiss/commit/8340ccdb1a0990b207d09a2518fccfb10d1542d4), thank you for notifying us.

**Comment by holoisme** [comment]
Fixed in [8340ccd](https://github.com/SnowWhiteEPFL/edweiss/commit/8340ccdb1a0990b207d09a2518fccfb10d1542d4), thank you for notifying us.
